version: '3'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - './api:/myapp'
      - './api/vendor/bundle:/myapp/vendor/bundle'
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    depends_on:
      - db
    environment:
      TZ: Asia/Tokyo
  db:
    image: mysql:8.0.33
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: 'Asia/Tokyo'
volumes:
  mysql_data:
