default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gahack_development
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: db

test:
  <<: *default
  database: gahack_test
  username: <%= ENV['DB_ROOT_USERNAME'] %>
  password: <%= ENV['DB_ROOT_PASSWORD'] %>
  host: db

production:
  <<: *default
  database: gahack_production
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
